# Generated by Django 4.2.5 on 2023-09-08 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='部活名')),
                ('image', models.ImageField(upload_to='', verbose_name='活動写真')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('introduction', models.CharField(max_length=150, verbose_name='紹介文')),
            ],
        ),
    ]
