# Generated by Django 4.2.5 on 2023-09-09 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_club_created_at_club_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='image',
            field=models.ImageField(upload_to='images/', verbose_name='活動写真'),
        ),
    ]
