# Generated by Django 4.2.5 on 2023-10-24 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_club_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='question',
            field=models.TextField(default='アンケート結果', max_length=300, verbose_name='アンケート'),
        ),
    ]
