# Generated by Django 4.2.5 on 2023-10-24 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_club_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='question',
            field=models.TextField(default='部長にアンケートを行いました!', max_length=300, verbose_name='アンケート'),
        ),
    ]
