# Generated by Django 4.2.5 on 2023-10-24 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_club_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='slug',
        ),
    ]
